/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CollectionRouteImport } from './routes/collection'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ContentRouteImport } from './routes/content'
import { Route as CouponRouteImport } from './routes/coupon'
import { Route as CustomerRouteImport } from './routes/customer'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as MessageRouteImport } from './routes/message'
import { Route as OrderRouteImport } from './routes/order'
import { Route as OrderConfirmedRouteImport } from './routes/order-confirmed'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as ProductRouteImport } from './routes/product'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as SettingRouteImport } from './routes/setting'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ShippingReturnsRouteImport } from './routes/shipping-returns'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SizeGuideRouteImport } from './routes/size-guide'
import { Route as TermsConditionsRouteImport } from './routes/terms-conditions'
import { Route as CustomerIndexRouteImport } from './routes/customer.index'
import { Route as CustomerIdRouteImport } from './routes/customer.$id'
import { Route as OrderIndexRouteImport } from './routes/order.index'
import { Route as OrderIdRouteImport } from './routes/order.$id'
import { Route as OrdersIndexRouteImport } from './routes/orders.index'
import { Route as OrdersIdRouteImport } from './routes/orders.$id'
import { Route as ProductNewRouteImport } from './routes/product.new'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as ProductIdEditRouteImport } from './routes/product.$id.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionRoute = CollectionRouteImport.update({
  id: '/collection',
  path: '/collection',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentRoute = ContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => rootRouteImport,
} as any)
const CouponRoute = CouponRouteImport.update({
  id: '/coupon',
  path: '/coupon',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerRoute = CustomerRouteImport.update({
  id: '/customer',
  path: '/customer',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const MessageRoute = MessageRouteImport.update({
  id: '/message',
  path: '/message',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderRoute = OrderRouteImport.update({
  id: '/order',
  path: '/order',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderConfirmedRoute = OrderConfirmedRouteImport.update({
  id: '/order-confirmed',
  path: '/order-confirmed',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductRoute = ProductRouteImport.update({
  id: '/product',
  path: '/product',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingRoute = SettingRouteImport.update({
  id: '/setting',
  path: '/setting',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingReturnsRoute = ShippingReturnsRouteImport.update({
  id: '/shipping-returns',
  path: '/shipping-returns',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SizeGuideRoute = SizeGuideRouteImport.update({
  id: '/size-guide',
  path: '/size-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsConditionsRoute = TermsConditionsRouteImport.update({
  id: '/terms-conditions',
  path: '/terms-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerIndexRoute = CustomerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerIdRoute = CustomerIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CustomerRoute,
} as any)
const OrderIndexRoute = OrderIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrderRoute,
} as any)
const OrderIdRoute = OrderIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => OrderRoute,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIdRoute = OrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductNewRoute = ProductNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ProductRoute,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdEditRoute = ProductIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => ProductRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/collection': typeof CollectionRoute
  '/contact': typeof ContactRoute
  '/content': typeof ContentRoute
  '/coupon': typeof CouponRoute
  '/customer': typeof CustomerRouteWithChildren
  '/faq': typeof FaqRoute
  '/message': typeof MessageRoute
  '/order': typeof OrderRouteWithChildren
  '/order-confirmed': typeof OrderConfirmedRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/product': typeof ProductRouteWithChildren
  '/review': typeof ReviewRoute
  '/reviews': typeof ReviewsRoute
  '/setting': typeof SettingRoute
  '/settings': typeof SettingsRoute
  '/shipping-returns': typeof ShippingReturnsRoute
  '/shop': typeof ShopRoute
  '/size-guide': typeof SizeGuideRoute
  '/terms-conditions': typeof TermsConditionsRoute
  '/customer/$id': typeof CustomerIdRoute
  '/order/$id': typeof OrderIdRoute
  '/orders/$id': typeof OrdersIdRoute
  '/product/new': typeof ProductNewRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/customer/': typeof CustomerIndexRoute
  '/order/': typeof OrderIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/product/$id/edit': typeof ProductIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/collection': typeof CollectionRoute
  '/contact': typeof ContactRoute
  '/content': typeof ContentRoute
  '/coupon': typeof CouponRoute
  '/faq': typeof FaqRoute
  '/message': typeof MessageRoute
  '/order-confirmed': typeof OrderConfirmedRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/product': typeof ProductRouteWithChildren
  '/review': typeof ReviewRoute
  '/reviews': typeof ReviewsRoute
  '/setting': typeof SettingRoute
  '/settings': typeof SettingsRoute
  '/shipping-returns': typeof ShippingReturnsRoute
  '/shop': typeof ShopRoute
  '/size-guide': typeof SizeGuideRoute
  '/terms-conditions': typeof TermsConditionsRoute
  '/customer/$id': typeof CustomerIdRoute
  '/order/$id': typeof OrderIdRoute
  '/orders/$id': typeof OrdersIdRoute
  '/product/new': typeof ProductNewRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/customer': typeof CustomerIndexRoute
  '/order': typeof OrderIndexRoute
  '/orders': typeof OrdersIndexRoute
  '/product/$id/edit': typeof ProductIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/collection': typeof CollectionRoute
  '/contact': typeof ContactRoute
  '/content': typeof ContentRoute
  '/coupon': typeof CouponRoute
  '/customer': typeof CustomerRouteWithChildren
  '/faq': typeof FaqRoute
  '/message': typeof MessageRoute
  '/order': typeof OrderRouteWithChildren
  '/order-confirmed': typeof OrderConfirmedRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/product': typeof ProductRouteWithChildren
  '/review': typeof ReviewRoute
  '/reviews': typeof ReviewsRoute
  '/setting': typeof SettingRoute
  '/settings': typeof SettingsRoute
  '/shipping-returns': typeof ShippingReturnsRoute
  '/shop': typeof ShopRoute
  '/size-guide': typeof SizeGuideRoute
  '/terms-conditions': typeof TermsConditionsRoute
  '/customer/$id': typeof CustomerIdRoute
  '/order/$id': typeof OrderIdRoute
  '/orders/$id': typeof OrdersIdRoute
  '/product/new': typeof ProductNewRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/customer/': typeof CustomerIndexRoute
  '/order/': typeof OrderIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/product/$id/edit': typeof ProductIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/analytics'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/collection'
    | '/contact'
    | '/content'
    | '/coupon'
    | '/customer'
    | '/faq'
    | '/message'
    | '/order'
    | '/order-confirmed'
    | '/privacy-policy'
    | '/product'
    | '/review'
    | '/reviews'
    | '/setting'
    | '/settings'
    | '/shipping-returns'
    | '/shop'
    | '/size-guide'
    | '/terms-conditions'
    | '/customer/$id'
    | '/order/$id'
    | '/orders/$id'
    | '/product/new'
    | '/products/$slug'
    | '/customer/'
    | '/order/'
    | '/orders/'
    | '/product/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/analytics'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/collection'
    | '/contact'
    | '/content'
    | '/coupon'
    | '/faq'
    | '/message'
    | '/order-confirmed'
    | '/privacy-policy'
    | '/product'
    | '/review'
    | '/reviews'
    | '/setting'
    | '/settings'
    | '/shipping-returns'
    | '/shop'
    | '/size-guide'
    | '/terms-conditions'
    | '/customer/$id'
    | '/order/$id'
    | '/orders/$id'
    | '/product/new'
    | '/products/$slug'
    | '/customer'
    | '/order'
    | '/orders'
    | '/product/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/analytics'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/collection'
    | '/contact'
    | '/content'
    | '/coupon'
    | '/customer'
    | '/faq'
    | '/message'
    | '/order'
    | '/order-confirmed'
    | '/privacy-policy'
    | '/product'
    | '/review'
    | '/reviews'
    | '/setting'
    | '/settings'
    | '/shipping-returns'
    | '/shop'
    | '/size-guide'
    | '/terms-conditions'
    | '/customer/$id'
    | '/order/$id'
    | '/orders/$id'
    | '/product/new'
    | '/products/$slug'
    | '/customer/'
    | '/order/'
    | '/orders/'
    | '/product/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AuthRoute: typeof AuthRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  CollectionRoute: typeof CollectionRoute
  ContactRoute: typeof ContactRoute
  ContentRoute: typeof ContentRoute
  CouponRoute: typeof CouponRoute
  CustomerRoute: typeof CustomerRouteWithChildren
  FaqRoute: typeof FaqRoute
  MessageRoute: typeof MessageRoute
  OrderRoute: typeof OrderRouteWithChildren
  OrderConfirmedRoute: typeof OrderConfirmedRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ProductRoute: typeof ProductRouteWithChildren
  ReviewRoute: typeof ReviewRoute
  ReviewsRoute: typeof ReviewsRoute
  SettingRoute: typeof SettingRoute
  SettingsRoute: typeof SettingsRoute
  ShippingReturnsRoute: typeof ShippingReturnsRoute
  ShopRoute: typeof ShopRoute
  SizeGuideRoute: typeof SizeGuideRoute
  TermsConditionsRoute: typeof TermsConditionsRoute
  OrdersIdRoute: typeof OrdersIdRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection': {
      id: '/collection'
      path: '/collection'
      fullPath: '/collection'
      preLoaderRoute: typeof CollectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content': {
      id: '/content'
      path: '/content'
      fullPath: '/content'
      preLoaderRoute: typeof ContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coupon': {
      id: '/coupon'
      path: '/coupon'
      fullPath: '/coupon'
      preLoaderRoute: typeof CouponRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer': {
      id: '/customer'
      path: '/customer'
      fullPath: '/customer'
      preLoaderRoute: typeof CustomerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/message': {
      id: '/message'
      path: '/message'
      fullPath: '/message'
      preLoaderRoute: typeof MessageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order': {
      id: '/order'
      path: '/order'
      fullPath: '/order'
      preLoaderRoute: typeof OrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-confirmed': {
      id: '/order-confirmed'
      path: '/order-confirmed'
      fullPath: '/order-confirmed'
      preLoaderRoute: typeof OrderConfirmedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product': {
      id: '/product'
      path: '/product'
      fullPath: '/product'
      preLoaderRoute: typeof ProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setting': {
      id: '/setting'
      path: '/setting'
      fullPath: '/setting'
      preLoaderRoute: typeof SettingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping-returns': {
      id: '/shipping-returns'
      path: '/shipping-returns'
      fullPath: '/shipping-returns'
      preLoaderRoute: typeof ShippingReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/size-guide': {
      id: '/size-guide'
      path: '/size-guide'
      fullPath: '/size-guide'
      preLoaderRoute: typeof SizeGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-conditions': {
      id: '/terms-conditions'
      path: '/terms-conditions'
      fullPath: '/terms-conditions'
      preLoaderRoute: typeof TermsConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/': {
      id: '/customer/'
      path: '/'
      fullPath: '/customer/'
      preLoaderRoute: typeof CustomerIndexRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/$id': {
      id: '/customer/$id'
      path: '/$id'
      fullPath: '/customer/$id'
      preLoaderRoute: typeof CustomerIdRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/order/': {
      id: '/order/'
      path: '/'
      fullPath: '/order/'
      preLoaderRoute: typeof OrderIndexRouteImport
      parentRoute: typeof OrderRoute
    }
    '/order/$id': {
      id: '/order/$id'
      path: '/$id'
      fullPath: '/order/$id'
      preLoaderRoute: typeof OrderIdRouteImport
      parentRoute: typeof OrderRoute
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$id': {
      id: '/orders/$id'
      path: '/orders/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof OrdersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/new': {
      id: '/product/new'
      path: '/new'
      fullPath: '/product/new'
      preLoaderRoute: typeof ProductNewRouteImport
      parentRoute: typeof ProductRoute
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id/edit': {
      id: '/product/$id/edit'
      path: '/$id/edit'
      fullPath: '/product/$id/edit'
      preLoaderRoute: typeof ProductIdEditRouteImport
      parentRoute: typeof ProductRoute
    }
  }
}

interface CustomerRouteChildren {
  CustomerIdRoute: typeof CustomerIdRoute
  CustomerIndexRoute: typeof CustomerIndexRoute
}

const CustomerRouteChildren: CustomerRouteChildren = {
  CustomerIdRoute: CustomerIdRoute,
  CustomerIndexRoute: CustomerIndexRoute,
}

const CustomerRouteWithChildren = CustomerRoute._addFileChildren(
  CustomerRouteChildren,
)

interface OrderRouteChildren {
  OrderIdRoute: typeof OrderIdRoute
  OrderIndexRoute: typeof OrderIndexRoute
}

const OrderRouteChildren: OrderRouteChildren = {
  OrderIdRoute: OrderIdRoute,
  OrderIndexRoute: OrderIndexRoute,
}

const OrderRouteWithChildren = OrderRoute._addFileChildren(OrderRouteChildren)

interface ProductRouteChildren {
  ProductNewRoute: typeof ProductNewRoute
  ProductIdEditRoute: typeof ProductIdEditRoute
}

const ProductRouteChildren: ProductRouteChildren = {
  ProductNewRoute: ProductNewRoute,
  ProductIdEditRoute: ProductIdEditRoute,
}

const ProductRouteWithChildren =
  ProductRoute._addFileChildren(ProductRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRoute,
  AnalyticsRoute: AnalyticsRoute,
  AuthRoute: AuthRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  CollectionRoute: CollectionRoute,
  ContactRoute: ContactRoute,
  ContentRoute: ContentRoute,
  CouponRoute: CouponRoute,
  CustomerRoute: CustomerRouteWithChildren,
  FaqRoute: FaqRoute,
  MessageRoute: MessageRoute,
  OrderRoute: OrderRouteWithChildren,
  OrderConfirmedRoute: OrderConfirmedRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ProductRoute: ProductRouteWithChildren,
  ReviewRoute: ReviewRoute,
  ReviewsRoute: ReviewsRoute,
  SettingRoute: SettingRoute,
  SettingsRoute: SettingsRoute,
  ShippingReturnsRoute: ShippingReturnsRoute,
  ShopRoute: ShopRoute,
  SizeGuideRoute: SizeGuideRoute,
  TermsConditionsRoute: TermsConditionsRoute,
  OrdersIdRoute: OrdersIdRoute,
  ProductsSlugRoute: ProductsSlugRoute,
  OrdersIndexRoute: OrdersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
